<?php
/**
 * RechnungsdruckWebAppControllersApiOrder
 *
 * PHP version 8.1
 *
 * @package  kruegge82\billbee
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billbee API
 *
 * Documentation of the Billbee REST API to connect a Billbee account to external aplications.  ## Endpoint  The Billbee API endpoint base url is https://api.billbee.io/api/v1   ## Activation  You have to enable the API in the settings of your Billbee account. In addition you need a Billbee API Key identifying the application you develop. To get an API key, send a mail to support@billbee.io and send us a short note about what you are building.  ## Authorization & security  Because you can access private data with the Billbee API, every request has to be sent over https and must  * Contain a valid API Key identifying the application/developer. It has to be sent as the HTTP header X-Billbee-Api-Key * Contain a valid user login with billbee username and api password in form of a basic auth HTTP header  ## Throttling  50 calls per second for each API Key.  10 calls per second for each API Key in combination with Billbee user.  Besides that each endpoint has a throttle of max 2 requests per second per combination of API Key and Billbee user.  When you exceed the throttle threshold, the API will return a HTTP 429 status code and a Retry-After-Header indicating how many seconds you will have to wait before you can call the API again.
 *
 * The version of the OpenAPI document: V1
 * Contact: support@billbee.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\billbee\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use kruegge82\billbee\ObjectSerializer;

/**
 * RechnungsdruckWebAppControllersApiOrder Class Doc Comment
 *
 * @package  kruegge82\billbee
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class RechnungsdruckWebAppControllersApiOrder implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'Rechnungsdruck.WebApp.Controllers.Api.Order';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'int',
        'external_id' => 'string',
        'invoice_number' => 'string',
        'invoice_created_at' => '\DateTime',
        'invoice_date' => '\DateTime',
        'created_at' => '\DateTime',
        'paid_at' => '\DateTime',
        'shipped_at' => '\DateTime',
        'has_invoice' => 'bool',
        'order_state_id' => 'int',
        'order_state_text' => 'string',
        'total_gross' => 'float',
        'shop_name' => 'string',
        'can_create_auto_invoice' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => 'int32',
        'external_id' => null,
        'invoice_number' => null,
        'invoice_created_at' => 'date-time',
        'invoice_date' => 'date-time',
        'created_at' => 'date-time',
        'paid_at' => 'date-time',
        'shipped_at' => 'date-time',
        'has_invoice' => null,
        'order_state_id' => 'int32',
        'order_state_text' => null,
        'total_gross' => 'double',
        'shop_name' => null,
        'can_create_auto_invoice' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => false,
        'external_id' => false,
        'invoice_number' => false,
        'invoice_created_at' => false,
        'invoice_date' => false,
        'created_at' => false,
        'paid_at' => false,
        'shipped_at' => false,
        'has_invoice' => false,
        'order_state_id' => false,
        'order_state_text' => false,
        'total_gross' => false,
        'shop_name' => false,
        'can_create_auto_invoice' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'Id',
        'external_id' => 'ExternalId',
        'invoice_number' => 'InvoiceNumber',
        'invoice_created_at' => 'InvoiceCreatedAt',
        'invoice_date' => 'InvoiceDate',
        'created_at' => 'CreatedAt',
        'paid_at' => 'PaidAt',
        'shipped_at' => 'ShippedAt',
        'has_invoice' => 'HasInvoice',
        'order_state_id' => 'OrderStateId',
        'order_state_text' => 'OrderStateText',
        'total_gross' => 'TotalGross',
        'shop_name' => 'ShopName',
        'can_create_auto_invoice' => 'CanCreateAutoInvoice'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'external_id' => 'setExternalId',
        'invoice_number' => 'setInvoiceNumber',
        'invoice_created_at' => 'setInvoiceCreatedAt',
        'invoice_date' => 'setInvoiceDate',
        'created_at' => 'setCreatedAt',
        'paid_at' => 'setPaidAt',
        'shipped_at' => 'setShippedAt',
        'has_invoice' => 'setHasInvoice',
        'order_state_id' => 'setOrderStateId',
        'order_state_text' => 'setOrderStateText',
        'total_gross' => 'setTotalGross',
        'shop_name' => 'setShopName',
        'can_create_auto_invoice' => 'setCanCreateAutoInvoice'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'external_id' => 'getExternalId',
        'invoice_number' => 'getInvoiceNumber',
        'invoice_created_at' => 'getInvoiceCreatedAt',
        'invoice_date' => 'getInvoiceDate',
        'created_at' => 'getCreatedAt',
        'paid_at' => 'getPaidAt',
        'shipped_at' => 'getShippedAt',
        'has_invoice' => 'getHasInvoice',
        'order_state_id' => 'getOrderStateId',
        'order_state_text' => 'getOrderStateText',
        'total_gross' => 'getTotalGross',
        'shop_name' => 'getShopName',
        'can_create_auto_invoice' => 'getCanCreateAutoInvoice'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array|null $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('external_id', $data ?? [], null);
        $this->setIfExists('invoice_number', $data ?? [], null);
        $this->setIfExists('invoice_created_at', $data ?? [], null);
        $this->setIfExists('invoice_date', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('paid_at', $data ?? [], null);
        $this->setIfExists('shipped_at', $data ?? [], null);
        $this->setIfExists('has_invoice', $data ?? [], null);
        $this->setIfExists('order_state_id', $data ?? [], null);
        $this->setIfExists('order_state_text', $data ?? [], null);
        $this->setIfExists('total_gross', $data ?? [], null);
        $this->setIfExists('shop_name', $data ?? [], null);
        $this->setIfExists('can_create_auto_invoice', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return $this
     */
    public function setId(?int $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets external_id
     *
     * @return string|null
     */
    public function getExternalId(): ?string
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string|null $external_id external_id
     *
     * @return $this
     */
    public function setExternalId(?string $external_id): static
    {
        if (is_null($external_id)) {
            throw new InvalidArgumentException('non-nullable external_id cannot be null');
        }
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets invoice_number
     *
     * @return string|null
     */
    public function getInvoiceNumber(): ?string
    {
        return $this->container['invoice_number'];
    }

    /**
     * Sets invoice_number
     *
     * @param string|null $invoice_number invoice_number
     *
     * @return $this
     */
    public function setInvoiceNumber(?string $invoice_number): static
    {
        if (is_null($invoice_number)) {
            throw new InvalidArgumentException('non-nullable invoice_number cannot be null');
        }
        $this->container['invoice_number'] = $invoice_number;

        return $this;
    }

    /**
     * Gets invoice_created_at
     *
     * @return \DateTime|null
     */
    public function getInvoiceCreatedAt(): ?\DateTime
    {
        return $this->container['invoice_created_at'];
    }

    /**
     * Sets invoice_created_at
     *
     * @param \DateTime|null $invoice_created_at invoice_created_at
     *
     * @return $this
     */
    public function setInvoiceCreatedAt(?\DateTime $invoice_created_at): static
    {
        if (is_null($invoice_created_at)) {
            throw new InvalidArgumentException('non-nullable invoice_created_at cannot be null');
        }
        $this->container['invoice_created_at'] = $invoice_created_at;

        return $this;
    }

    /**
     * Gets invoice_date
     *
     * @return \DateTime|null
     */
    public function getInvoiceDate(): ?\DateTime
    {
        return $this->container['invoice_date'];
    }

    /**
     * Sets invoice_date
     *
     * @param \DateTime|null $invoice_date invoice_date
     *
     * @return $this
     */
    public function setInvoiceDate(?\DateTime $invoice_date): static
    {
        if (is_null($invoice_date)) {
            throw new InvalidArgumentException('non-nullable invoice_date cannot be null');
        }
        $this->container['invoice_date'] = $invoice_date;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at created_at
     *
     * @return $this
     */
    public function setCreatedAt(?\DateTime $created_at): static
    {
        if (is_null($created_at)) {
            throw new InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets paid_at
     *
     * @return \DateTime|null
     */
    public function getPaidAt(): ?\DateTime
    {
        return $this->container['paid_at'];
    }

    /**
     * Sets paid_at
     *
     * @param \DateTime|null $paid_at paid_at
     *
     * @return $this
     */
    public function setPaidAt(?\DateTime $paid_at): static
    {
        if (is_null($paid_at)) {
            throw new InvalidArgumentException('non-nullable paid_at cannot be null');
        }
        $this->container['paid_at'] = $paid_at;

        return $this;
    }

    /**
     * Gets shipped_at
     *
     * @return \DateTime|null
     */
    public function getShippedAt(): ?\DateTime
    {
        return $this->container['shipped_at'];
    }

    /**
     * Sets shipped_at
     *
     * @param \DateTime|null $shipped_at shipped_at
     *
     * @return $this
     */
    public function setShippedAt(?\DateTime $shipped_at): static
    {
        if (is_null($shipped_at)) {
            throw new InvalidArgumentException('non-nullable shipped_at cannot be null');
        }
        $this->container['shipped_at'] = $shipped_at;

        return $this;
    }

    /**
     * Gets has_invoice
     *
     * @return bool|null
     */
    public function getHasInvoice(): ?bool
    {
        return $this->container['has_invoice'];
    }

    /**
     * Sets has_invoice
     *
     * @param bool|null $has_invoice has_invoice
     *
     * @return $this
     */
    public function setHasInvoice(?bool $has_invoice): static
    {
        if (is_null($has_invoice)) {
            throw new InvalidArgumentException('non-nullable has_invoice cannot be null');
        }
        $this->container['has_invoice'] = $has_invoice;

        return $this;
    }

    /**
     * Gets order_state_id
     *
     * @return int|null
     */
    public function getOrderStateId(): ?int
    {
        return $this->container['order_state_id'];
    }

    /**
     * Sets order_state_id
     *
     * @param int|null $order_state_id order_state_id
     *
     * @return $this
     */
    public function setOrderStateId(?int $order_state_id): static
    {
        if (is_null($order_state_id)) {
            throw new InvalidArgumentException('non-nullable order_state_id cannot be null');
        }
        $this->container['order_state_id'] = $order_state_id;

        return $this;
    }

    /**
     * Gets order_state_text
     *
     * @return string|null
     */
    public function getOrderStateText(): ?string
    {
        return $this->container['order_state_text'];
    }

    /**
     * Sets order_state_text
     *
     * @param string|null $order_state_text order_state_text
     *
     * @return $this
     */
    public function setOrderStateText(?string $order_state_text): static
    {
        if (is_null($order_state_text)) {
            throw new InvalidArgumentException('non-nullable order_state_text cannot be null');
        }
        $this->container['order_state_text'] = $order_state_text;

        return $this;
    }

    /**
     * Gets total_gross
     *
     * @return float|null
     */
    public function getTotalGross(): ?float
    {
        return $this->container['total_gross'];
    }

    /**
     * Sets total_gross
     *
     * @param float|null $total_gross total_gross
     *
     * @return $this
     */
    public function setTotalGross(?float $total_gross): static
    {
        if (is_null($total_gross)) {
            throw new InvalidArgumentException('non-nullable total_gross cannot be null');
        }
        $this->container['total_gross'] = $total_gross;

        return $this;
    }

    /**
     * Gets shop_name
     *
     * @return string|null
     */
    public function getShopName(): ?string
    {
        return $this->container['shop_name'];
    }

    /**
     * Sets shop_name
     *
     * @param string|null $shop_name shop_name
     *
     * @return $this
     */
    public function setShopName(?string $shop_name): static
    {
        if (is_null($shop_name)) {
            throw new InvalidArgumentException('non-nullable shop_name cannot be null');
        }
        $this->container['shop_name'] = $shop_name;

        return $this;
    }

    /**
     * Gets can_create_auto_invoice
     *
     * @return bool|null
     */
    public function getCanCreateAutoInvoice(): ?bool
    {
        return $this->container['can_create_auto_invoice'];
    }

    /**
     * Sets can_create_auto_invoice
     *
     * @param bool|null $can_create_auto_invoice can_create_auto_invoice
     *
     * @return $this
     */
    public function setCanCreateAutoInvoice(?bool $can_create_auto_invoice): static
    {
        if (is_null($can_create_auto_invoice)) {
            throw new InvalidArgumentException('non-nullable can_create_auto_invoice cannot be null');
        }
        $this->container['can_create_auto_invoice'] = $can_create_auto_invoice;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


