<?php
/**
 * BillbeeInterfacesBillbeeAPIModelInvoiceApiPositionApiModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  kruegge82\billbee
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billbee API
 *
 * Documentation of the Billbee REST API to connect a Billbee account to external aplications.  ## Endpoint  The Billbee API endpoint base url is https://api.billbee.io/api/v1   ## Activation  You have to enable the API in the settings of your Billbee account. In addition you need a Billbee API Key identifying the application you develop. To get an API key, send a mail to support@billbee.io and send us a short note about what you are building.  ## Authorization & security  Because you can access private data with the Billbee API, every request has to be sent over https and must  * Contain a valid API Key identifying the application/developer. It has to be sent as the HTTP header X-Billbee-Api-Key * Contain a valid user login with billbee username and api password in form of a basic auth HTTP header  ## Throttling  50 calls per second for each API Key.  10 calls per second for each API Key in combination with Billbee user.  Besides that each endpoint has a throttle of max 2 requests per second per combination of API Key and Billbee user.  When you exceed the throttle threshold, the API will return a HTTP 429 status code and a Retry-After-Header indicating how many seconds you will have to wait before you can call the API again.
 *
 * The version of the OpenAPI document: V1
 * Contact: support@billbee.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\billbee\Model;

use \ArrayAccess;
use \kruegge82\billbee\ObjectSerializer;

/**
 * BillbeeInterfacesBillbeeAPIModelInvoiceApiPositionApiModel Class Doc Comment
 *
 * @category Class
 * @package  kruegge82\billbee
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BillbeeInterfacesBillbeeAPIModelInvoiceApiPositionApiModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Billbee.Interfaces.BillbeeAPI.Model.InvoiceApiPositionApiModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'position' => 'int',
        'amount' => 'float',
        'net_value' => 'float',
        'total_net_value' => 'float',
        'gross_value' => 'float',
        'total_gross_value' => 'float',
        'vat_rate' => 'float',
        'article_billbee_id' => 'int',
        'sku' => 'string',
        'title' => 'string',
        'billbee_id' => 'int',
        'total_vat_amount' => 'float',
        'rebate_percent' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'position' => 'int32',
        'amount' => 'double',
        'net_value' => 'double',
        'total_net_value' => 'double',
        'gross_value' => 'double',
        'total_gross_value' => 'double',
        'vat_rate' => 'double',
        'article_billbee_id' => 'int32',
        'sku' => null,
        'title' => null,
        'billbee_id' => 'int64',
        'total_vat_amount' => 'double',
        'rebate_percent' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'position' => false,
        'amount' => false,
        'net_value' => false,
        'total_net_value' => false,
        'gross_value' => false,
        'total_gross_value' => false,
        'vat_rate' => false,
        'article_billbee_id' => false,
        'sku' => false,
        'title' => false,
        'billbee_id' => false,
        'total_vat_amount' => false,
        'rebate_percent' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'position' => 'Position',
        'amount' => 'Amount',
        'net_value' => 'NetValue',
        'total_net_value' => 'TotalNetValue',
        'gross_value' => 'GrossValue',
        'total_gross_value' => 'TotalGrossValue',
        'vat_rate' => 'VatRate',
        'article_billbee_id' => 'ArticleBillbeeId',
        'sku' => 'Sku',
        'title' => 'Title',
        'billbee_id' => 'BillbeeId',
        'total_vat_amount' => 'TotalVatAmount',
        'rebate_percent' => 'RebatePercent'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'position' => 'setPosition',
        'amount' => 'setAmount',
        'net_value' => 'setNetValue',
        'total_net_value' => 'setTotalNetValue',
        'gross_value' => 'setGrossValue',
        'total_gross_value' => 'setTotalGrossValue',
        'vat_rate' => 'setVatRate',
        'article_billbee_id' => 'setArticleBillbeeId',
        'sku' => 'setSku',
        'title' => 'setTitle',
        'billbee_id' => 'setBillbeeId',
        'total_vat_amount' => 'setTotalVatAmount',
        'rebate_percent' => 'setRebatePercent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'position' => 'getPosition',
        'amount' => 'getAmount',
        'net_value' => 'getNetValue',
        'total_net_value' => 'getTotalNetValue',
        'gross_value' => 'getGrossValue',
        'total_gross_value' => 'getTotalGrossValue',
        'vat_rate' => 'getVatRate',
        'article_billbee_id' => 'getArticleBillbeeId',
        'sku' => 'getSku',
        'title' => 'getTitle',
        'billbee_id' => 'getBillbeeId',
        'total_vat_amount' => 'getTotalVatAmount',
        'rebate_percent' => 'getRebatePercent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('position', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('net_value', $data ?? [], null);
        $this->setIfExists('total_net_value', $data ?? [], null);
        $this->setIfExists('gross_value', $data ?? [], null);
        $this->setIfExists('total_gross_value', $data ?? [], null);
        $this->setIfExists('vat_rate', $data ?? [], null);
        $this->setIfExists('article_billbee_id', $data ?? [], null);
        $this->setIfExists('sku', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('billbee_id', $data ?? [], null);
        $this->setIfExists('total_vat_amount', $data ?? [], null);
        $this->setIfExists('rebate_percent', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets position
     *
     * @return int|null
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     *
     * @param int|null $position position
     *
     * @return self
     */
    public function setPosition($position)
    {
        if (is_null($position)) {
            throw new \InvalidArgumentException('non-nullable position cannot be null');
        }
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return float|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float|null $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets net_value
     *
     * @return float|null
     */
    public function getNetValue()
    {
        return $this->container['net_value'];
    }

    /**
     * Sets net_value
     *
     * @param float|null $net_value net_value
     *
     * @return self
     */
    public function setNetValue($net_value)
    {
        if (is_null($net_value)) {
            throw new \InvalidArgumentException('non-nullable net_value cannot be null');
        }
        $this->container['net_value'] = $net_value;

        return $this;
    }

    /**
     * Gets total_net_value
     *
     * @return float|null
     */
    public function getTotalNetValue()
    {
        return $this->container['total_net_value'];
    }

    /**
     * Sets total_net_value
     *
     * @param float|null $total_net_value total_net_value
     *
     * @return self
     */
    public function setTotalNetValue($total_net_value)
    {
        if (is_null($total_net_value)) {
            throw new \InvalidArgumentException('non-nullable total_net_value cannot be null');
        }
        $this->container['total_net_value'] = $total_net_value;

        return $this;
    }

    /**
     * Gets gross_value
     *
     * @return float|null
     */
    public function getGrossValue()
    {
        return $this->container['gross_value'];
    }

    /**
     * Sets gross_value
     *
     * @param float|null $gross_value gross_value
     *
     * @return self
     */
    public function setGrossValue($gross_value)
    {
        if (is_null($gross_value)) {
            throw new \InvalidArgumentException('non-nullable gross_value cannot be null');
        }
        $this->container['gross_value'] = $gross_value;

        return $this;
    }

    /**
     * Gets total_gross_value
     *
     * @return float|null
     */
    public function getTotalGrossValue()
    {
        return $this->container['total_gross_value'];
    }

    /**
     * Sets total_gross_value
     *
     * @param float|null $total_gross_value total_gross_value
     *
     * @return self
     */
    public function setTotalGrossValue($total_gross_value)
    {
        if (is_null($total_gross_value)) {
            throw new \InvalidArgumentException('non-nullable total_gross_value cannot be null');
        }
        $this->container['total_gross_value'] = $total_gross_value;

        return $this;
    }

    /**
     * Gets vat_rate
     *
     * @return float|null
     */
    public function getVatRate()
    {
        return $this->container['vat_rate'];
    }

    /**
     * Sets vat_rate
     *
     * @param float|null $vat_rate vat_rate
     *
     * @return self
     */
    public function setVatRate($vat_rate)
    {
        if (is_null($vat_rate)) {
            throw new \InvalidArgumentException('non-nullable vat_rate cannot be null');
        }
        $this->container['vat_rate'] = $vat_rate;

        return $this;
    }

    /**
     * Gets article_billbee_id
     *
     * @return int|null
     */
    public function getArticleBillbeeId()
    {
        return $this->container['article_billbee_id'];
    }

    /**
     * Sets article_billbee_id
     *
     * @param int|null $article_billbee_id article_billbee_id
     *
     * @return self
     */
    public function setArticleBillbeeId($article_billbee_id)
    {
        if (is_null($article_billbee_id)) {
            throw new \InvalidArgumentException('non-nullable article_billbee_id cannot be null');
        }
        $this->container['article_billbee_id'] = $article_billbee_id;

        return $this;
    }

    /**
     * Gets sku
     *
     * @return string|null
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     *
     * @param string|null $sku sku
     *
     * @return self
     */
    public function setSku($sku)
    {
        if (is_null($sku)) {
            throw new \InvalidArgumentException('non-nullable sku cannot be null');
        }
        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets billbee_id
     *
     * @return int|null
     */
    public function getBillbeeId()
    {
        return $this->container['billbee_id'];
    }

    /**
     * Sets billbee_id
     *
     * @param int|null $billbee_id billbee_id
     *
     * @return self
     */
    public function setBillbeeId($billbee_id)
    {
        if (is_null($billbee_id)) {
            throw new \InvalidArgumentException('non-nullable billbee_id cannot be null');
        }
        $this->container['billbee_id'] = $billbee_id;

        return $this;
    }

    /**
     * Gets total_vat_amount
     *
     * @return float|null
     */
    public function getTotalVatAmount()
    {
        return $this->container['total_vat_amount'];
    }

    /**
     * Sets total_vat_amount
     *
     * @param float|null $total_vat_amount total_vat_amount
     *
     * @return self
     */
    public function setTotalVatAmount($total_vat_amount)
    {
        if (is_null($total_vat_amount)) {
            throw new \InvalidArgumentException('non-nullable total_vat_amount cannot be null');
        }
        $this->container['total_vat_amount'] = $total_vat_amount;

        return $this;
    }

    /**
     * Gets rebate_percent
     *
     * @return float|null
     */
    public function getRebatePercent()
    {
        return $this->container['rebate_percent'];
    }

    /**
     * Sets rebate_percent
     *
     * @param float|null $rebate_percent rebate_percent
     *
     * @return self
     */
    public function setRebatePercent($rebate_percent)
    {
        if (is_null($rebate_percent)) {
            throw new \InvalidArgumentException('non-nullable rebate_percent cannot be null');
        }
        $this->container['rebate_percent'] = $rebate_percent;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


